- platform: mqtt
  name: "Light 1"
  command_topic: "cmnd/light01/POWER"
  state_topic: "stat/light01/POWER"
#  state_value_template: "{{value_json.POWER}}"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/light01/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  brightness_command_topic: "cmnd/light01/Dimmer"
  brightness_state_topic: "stat/light01/RESULT"
  brightness_scale: 100
#  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  rgb_command_topic: "cmnd/light01/Color2"
  rgb_state_topic: "tele/light01/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/light01/Scheme"
  effect_state_topic: "tele/light01/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0 # single color for LED light (default)
    - 1 # start wake up sequence (same as Wakeup)
    - 2 # cycle up through colors using Speed option
    - 3 # cycle down through colors using Speed option
    - 4 # random cycle through colors using Speed and Fade
  qos: 0
  retain: true
  optimistic: false