---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Home Control Panel
resources: !include_dir_list lovelace/resources
      
views:

 - !include lovelace/views/home.yaml
 - !include lovelace/views/security.yaml 
 - !include lovelace/views/audio.yaml
 #- !include lovelace/views/radar.yaml
 - !include lovelace/views/network.yaml
 - !include lovelace/views/other.yaml
 - !include lovelace/views/controls.yaml
 - !include lovelace/views/internals.yaml
 - !include lovelace/views/automations.yaml
 - !include lovelace/views/dev.yaml 