

title: Automations
icon: mdi:settings-outline
columns: 5
cards:
  - type: 'custom:compact-custom-header'    


#----------------------------------


  - type: vertical-stack
    cards:
    - type: custom:monster-card
      card:
        type: entities
        title: Automations
        show_header_toggle: false  
      filter:
        include:
          - domain: automation
            options:
              secondary_info: last-changed
    - type: entities
      entities:
          - sensor.automation_count
          
  - type: entities
    title: Settings
    show_header_toggle: false
    entities:
      - input_boolean.sleep_mode
      - input_boolean.guest_mode
      - input_boolean.vacation_mode
      
  - type: entities
    title: Scripts
    show_header_toggle: false
    entities:
      - entity: group.all_scripts