

title: Dev
icon: mdi:lead-pencil
cards:
    
  - type: entities
    title: Home Assistant
    show_header_toggle: false        
    entities: 
      - sensor.version_current
      - sensor.version_available
      - script.restart
      
#----------------------------------

  - type: entities
    title: Stats
    show_header_toggle: false
    entities:
      - sensor.sensor_count
      - sensor.automation_count
      - sensor.script_count
      - sensor.switch_count
      - sensor.binary_sensor_count
      - sensor.lights_count
      - sensor.tracker_count
      - sensor.home_assistant_log
      - sensor.home_assistant_v2_db
      - script.db_purge
          
#-------------------------------------

  - type: custom:tracker-card
  
#----------------------------------

  - type: entities
    title: Development Links
    
    show_header_toggle: false
    entities:
      - type: weblink
        name: Home Assistant
        url: https://www.home-assistant.io/
        icon: mdi:home-assistant
      - type: weblink
        name: Home Assistant Editor
        url: http://192.168.1.107:8123/hassio/ingress/core_configurator
        icon: mdi:home-assistant
      - type: weblink
        name: MDI Icons
        url: https://materialdesignicons.com/
        icon: mdi:home-assistant
      - type: weblink
        name: Awesome HA
        url: https://www.awesome-ha.com/
        icon: mdi:home-assistant 
      - type: weblink
        name: TasmoAdmin
        url: http://192.168.1.107:9541
        icon: mdi:home-assistant  
      - type: weblink
        name: Tasmota Wiki
        url: https://github.com/arendst/Sonoff-Tasmota/wiki
        icon: mdi:home-assistant

#-----------------------------------

  - type: entities
    title: Internal Links
    show_header_toggle: false
    entities:
      - type: weblink
        name: Citadel
        url: http://192.168.1.209
        icon: mdi:email
      - type: weblink
        name: Syncthing Big-Server
        url: https://192.168.1.125:8384
        icon: mdi:folder-sync
      - type: weblink
        name: Syncthing Fileserver
        url: https://192.168.1.205:8384
        icon: mdi:folder-sync
      - type: weblink
        name: Syncthing Laptop
        url: https://localhost:8080
        icon: mdi:folder-sync
      - type: weblink
        name: Octoprint
        url: http://192.168.1.114
        icon: mdi:printer-3d
      - type: weblink
        name: MotionEye
        url: http://192.168.1.207:8765
        icon: mdi:cctv
      - type: weblink
        name: OwnCloud
        url: https://192.168.1.203/index.php/login
        icon: mdi:cloud
      - type: weblink
        name: Proxmox
        url: https://192.168.1.121:8006
        icon: mdi:server
      - type: weblink
        name: Rhasspy
        url: http://192.168.1.211:12101
        icon: mdi:voice
      - type: weblink
        name: PiHole
        url: http://192.168.1.210/admin
        icon: mdi:pi-hole
      - type: weblink
        name: Router
        url: http://192.168.1.1
        icon: mdi:router-wireless  
    
#------------------------------------

  - type: entities
    title: Other Links
    show_header_toggle: false
    entities:
      - type: weblink
        name: YouTube Links
        url: http://192.168.1.204/you.html
      - type: weblink
        name: Raw MQTT feed
        url: http://192.168.1.204/rfeed.html
      - type: weblink
        name: Tree View of MQTT
        url: http://192.168.1.204/tree.html
      - type: weblink
        name: FindU
        url: !secret TRUCK_URL1
      - type: weblink
        name: APRS Fi
        url: !secret TRUCK_URL2 
      - type: weblink
        name: APRS Direct
        url: !secret TRUCK_URL3 
      - type: weblink
        name: Road Conditions
        url: https://hb.511ia.org/#plowHome?layers=winterDriving%2CimagePlows%2ClocationPlows&timeFrame=TODAY


#--------------------------------------

  - type: entities
    title: Test Harness
    show_header_toggle: false
    entities:
      - entity: input_boolean.test