#================================

title: Security
icon: mdi:cctv
panel: true

cards:
  - type: vertical-stack
    cards:
      - type: iframe
        url: 'http://192.168.1.207:8765'
      - type: custom:compact-custom-header


