- platform: mqtt
  name: "D7mini07 LED State"
  state_topic: "stat/D7mini07/RESULT"
  value_template: "{{ value_json.LedPower }}"
  command_topic: "cmnd/D7mini07/LedPower"
  availability_topic: "tele/D7mini07/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false