- platform: mqtt
  name: "D1mini1 LED State"
  state_topic: "stat/D1mini1/RESULT"
  value_template: "{{ value_json.LedState }}"
  command_topic: "cmnd/D1mini1/LedState"
  availability_topic: "tele/D1mini1/LWT"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false