- platform: mqtt
  name: "D3mini03 LED State"
  state_topic: "stat/D3mini03/RESULT"
  value_template: "{{ value_json.LedPower }}"
  command_topic: "cmnd/D3mini03/LedPower"
  availability_topic: "tele/D3mini03/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false