- platform: mqtt
  name: "D1mini01 LED State"
  state_topic: "stat/D1mini01/RESULT"
  value_template: "{{ value_json.LedPower }}"
  command_topic: "cmnd/D1mini01/LedPower"
  availability_topic: "tele/D1mini01/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false