- platform: mqtt
  name: "D4mini04 LED State"
  state_topic: "stat/D4mini04/RESULT"
  value_template: "{{ value_json.LedPower }}"
  command_topic: "cmnd/D4mini04/LedPower"
  availability_topic: "tele/D4mini04/LWT"
  qos: 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false