- platform: mqtt
  name: "ESPxx01 LED State"
  state_topic: "stat/ESPxx01/RESULT"
  value_template: "{{ value_json.LedPower }}"
  command_topic: "cmnd/ESPxx01/LedPower"
  availability_topic: "tele/ESPxx01/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false