- platform: mqtt
  name: "ESPxx02 LED State"
  state_topic: "stat/ESPxx02/RESULT"
  value_template: "{{ value_json.LedPower }}"
  command_topic: "cmnd/ESPxx02/LedPower"
  availability_topic: "tele/ESPxx02/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false