- platform: mqtt
  name: "ESPxx03 Power State"
  state_topic: "stat/ESPxx03/POWER"
#  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/ESPxx03/POWER"
  availability_topic: "tele/ESPxx03/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
  
- platform: mqtt
  name: "ESPxx03 LED State"
  state_topic: "stat/ESPxx03/RESULT"
  value_template: "{{ value_json.LedPower }}"
  command_topic: "cmnd/ESPxx03/LedPower"
  availability_topic: "tele/ESPxx03/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false