- platform: mqtt
  name: "ESPxx06 Power State"
  state_topic: "stat/ESPxx06/POWER"
#  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/ESPxx06/POWER"
  availability_topic: "tele/ESPxx06/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
  
- platform: mqtt
  name: "ESPxx06 LED State"
  state_topic: "stat/ESPxx06/RESULT"
  value_template: "{{ value_json.LedPower }}"
  command_topic: "cmnd/ESPxx06/LedPower"
  availability_topic: "tele/ESPxx06/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false