  
- platform: mqtt
  name: "Sonoff2 Power State"
  state_topic: "tele/sonoff2/STATE"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoff2/POWER"
  availability_topic: "tele/sonoff2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
