- platform: mqtt
  name: "Sonoff1 Power State"
  state_topic: "tele/sonoff1/STATE"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoff1/POWER"
  availability_topic: "tele/sonoff1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
