      
- alias: Aurora Visibility Notification 
  trigger:
  - platform: state
    entity_id: binary_sensor.aurora_visibility
    from: 'off'
    to: 'on'
  action:
  - service: script.zanzito_say
    data_template:
      dest_id: "DennisPhone" 
      message: >
                There is currently a {{ states.binary_sensor.aurora_visibility.attributes.visibility_level }} % chance of viewing auroras.  
                {{ "\n" }}
                {{ states.binary_sensor.aurora_visibility.attributes.message }}
  - service: persistent_notification.create
    data_template:
      message: >
                There is currently a {{ states.binary_sensor.aurora_visibility.attributes.visibility_level }} % chance of viewing auroras.  
                {{ "\n" }}
                {{ states.binary_sensor.aurora_visibility.attributes.message }}
      title: "Aurora Alert"
      notification_id: "aurora_alert" 
      
      
- alias: Aurora Notification Expiration
  trigger:
  - platform: state
    entity_id: binary_sensor.aurora_visibility
    from: 'on'
    to: 'off'
  action:
  - service: script.zanzito_say
    data_template:
      dest_id: "DennisPhone" 
      message: >
                The chance of viewing auroras has passed.
  - service: persistent_notification.dismiss
    data:
      notification_id: "aurora_alert" 