      
- alias: Aurora Notification
  trigger:
  - platform: state
    entity_id: binary_sensor.aurora_visibility
    from: 'off'
    to: 'on'
  action:
  - service: script.zanzito_say
    data:
      dest_id: "DennisPhone" 
      message: >
                There is currently a {{state_attr('binary_sensor.aurora_visibility', 'visibility_level')}} % chance of viewing auroras.  
                {{ "\n" }}
                {{state_attr('binary_sensor.aurora_visibility', 'message')}}
  - service: persistent_notification.create
    data:
      message: "There is a possibility of aurora visibility currently!"
      title: "Aurora Alert"
      notification_id: "aurora_alert" 