
- alias: Clock Voice
  trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '0'
    - platform: time_pattern
      minutes: '15'
    - platform: time_pattern
      minutes: '30'
    - platform: time_pattern
      minutes: '45'
  condition:
    - condition: state
      entity_id: 'input_boolean.sleep_mode'
      state: 'off'
    - condition: state
      entity_id: 'input_boolean.mute_mode'
      state: 'off'    
    - condition: state
      entity_id: 'input_boolean.theater_mode'
      state: 'off'     
  action:
    - service: notify.voice
      data_template:
        message: >
          The time is now
          {% if now().strftime("%H")|int > 12 %}
            {% set PM = true %}
            {% set hour = now().strftime("%H")|int - 12 %}
          {% else %}
            {% set hour = now().strftime("%H")|int %}
          {% endif %}
          {% if now().strftime("%M")|int == 0 %}
            {% if hour == 0 %}
            midnight
            {% elif hour == 12 %}
            noon
            {% else %}
            {{ hour }} O'clock
            {% endif %}
          {% elif now().strftime("%M")|int == 15 %}
            {% if hour == 0 %}
            {% set hour = "midnight" %}
            {% elif hour == 12 %}
            {% set hour = "noon" %}
            {% endif %}          
            a quarter after {{ hour }}
          {% elif now().strftime("%M")|int == 30 %}
            {% if hour == 0 %}
            12 thirty
            {% else %}
            {{ hour }} thirty
            {% endif %}
          {% elif now().strftime("%M")|int == 45 %}
            {% set hour = hour + 1 %}
            {% if hour > 12 %}
              {% set hour = hour - 12 %}
              {% set PM = true %}
            {% endif %}
            {% if hour == 0 %}
            {% set hour = "midnight" %}
            {% elif hour == 12 %}
            {% set hour = "noon" %}
            {% endif %}
            a quarter til {{ hour }}
          {% endif %}
#          {% if PM == true %}
#            Pee eMm
 #         {% else %}
 #           Aay eMm
 #         {% endif %}'
        dest_id: default