###################################
##  cuckoo Clock simulation.
## Plays the number of cuckoos per hour and 1 on the half hour.
###################################

- alias: Clock Cuckoo
  trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '0'
    - platform: time_pattern
      minutes: '30'
  condition:
    - condition: state
      entity_id: 'input_boolean.sleep_mode'
      state: 'off'
    - condition: state
      entity_id: 'input_boolean.mute_mode'
      state: 'off'    
    - condition: state
      entity_id: 'input_boolean.theater_mode'
      state: 'off' 
  action:
    - service: shell_command.play
      data_template:
        file: >
          {% if now().strftime("%M")|int == 30 %}
          /config/audio/cuckoo-clock-01.wav
          {% else %}
          /config/audio/cuckoo-clock-{{now().strftime("%I")}}.wav
          {% endif %}
