
- alias: Clock Grandfather
  trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '0'
    - platform: time_pattern
      minutes: '15'
    - platform: time_pattern
      minutes: '45'
    - platform: time_pattern
      minutes: '30'
  condition:
    - condition: state
      entity_id: 'input_boolean.sleep_mode'
      state: 'off'
    - condition: state
      entity_id: 'input_boolean.mute_mode'
      state: 'off'    
    - condition: state
      entity_id: 'input_boolean.theater_mode'
      state: 'off' 
  action:
    - service: shell_command.play
      data_template:
        file: >
            {% if now().strftime('%M')|int == 15 %}
            /config/audio/Toll-1Quarter.wav
            {% elif  now().strftime('%M')|int == 30 %}
            /config/audio/Toll-2Quarter.wav
            {% elif  now().strftime('%M')|int == 45 %}
            /config/audio/Toll-3Quarter.wav
            {% else %}
            /config/audio/{{now().strftime('%I')}}-hour.wav
            {% endif %}
          
          