
- alias: Clock Big Ben
  trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '0'
    - platform: time_pattern
      minutes: '30'
  condition:
    - condition: state
      entity_id: 'input_boolean.sleep_mode'
      state: 'off'
    - condition: state
      entity_id: 'input_boolean.mute_mode'
      state: 'off'    
    - condition: state
      entity_id: 'input_boolean.theater_mode'
      state: 'off' 
  action:
    - service: script.amp_settings
      data:
        media_player: 'media_player.media_player_1'
        volume_level: 0.2
    - service: media_player.play_media
      data_template:
        entity_id: >
          media_player.media_player_1
        media_content_id: >
          {% if now().strftime("%M")|int == 30 %}
          /config/audio/cuckoo-clock-01.wav
          {% else %}
          /config/audio/cuckoo-clock-{{now().strftime("%I")}}.wav
          {% endif %}
        media_content_type: audio/mp4