
- alias: Clock Big Ben
  trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '0'
    - platform: time_pattern
      minutes: '30'
  condition:
    - condition: state
      entity_id: 'input_boolean.sleep_mode'
      state: 'off'
    - condition: state
      entity_id: 'input_boolean.mute_mode'
      state: 'off'    
    - condition: state
      entity_id: 'input_boolean.theater_mode'
      state: 'off' 
  action:
    - service: script.amp_settings
      data:
        media_player: 'media_player.livingroomcc'
        volume_level: 0.22

    - service: media_player.play_media
      data_template:
        entity_id: >
          {% if states.group.bed.state == 'off' %}
          media_player.livingroomCC
          {% else %}
          media_player.alarm_clock, media_player.bedroom_alarm_panel
          {% endif %}
        media_content_id: >
          {% if now().strftime("%M")|int == 30 %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/cuckoo-clock-01.wav
          {% else %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/cuckoo-clock-{{now().strftime("%I")}}.wav
          {% endif %}
        media_content_type: audio/mp4