
- alias: Clock Grandfather
  trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '0'
    - platform: time_pattern
      minutes: 15
    - platform: time_pattern
      minutes: 45
    - platform: time_pattern
      minutes: '30'
  condition:
    - condition: state
      entity_id: 'input_boolean.sleep_mode'
      state: 'off'
    - condition: state
      entity_id: 'input_boolean.mute_mode'
      state: 'off'    
    - condition: state
      entity_id: 'input_boolean.theater_mode'
      state: 'off' 
  action:
#    - service: script.amp_settings
#      data:
#        media_player: 'media_player.media_player_1'
#        volume_level: 0.2
    - service: media_player.play_media
      data_template:
        entity_id: >
          media_player.media_player_1
        media_content_id: >
          {% if now().strftime("%M")|int == 15 %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/gf_clock/Toll-1Quarter.mp3
          {% elif  now().strftime("%M")|int == 30 %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/gf_clock/Toll-2Quarter.mp3       
          {% elif  now().strftime("%M")|int == 45 %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/gf_clock/Toll-3Quarter.mp3           
          {% else %}
          https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/gf_clock/{{now().strftime("%I")}}-hour.mp3
          {% endif %}
        media_content_type: audio/mp4