
- alias: "Initialize HA"
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: script.refresh_sonoffs
  - service: script.refresh_phones
  - service: climate.set_away_mode
    data:
      entity_id: climate.grafting_thermostat
      away_mode: 'off'
  - service: climate.set_temperature
    data:
      entity_id: climate.grafting_thermostat
      temperature: 45