- alias: 'Intent Chit Chat - thank you'
  trigger:
    platform: event
    event_type: rhasspy_ThankYou
  action:
    service: shell_command.say
    data_template:
      dest_id: default
      message: >-
        '{% set responses = [
        "Youre welcome",
        "You got it",
        "Dont mention it",
        "No worries",
        "Not a problem",
        "Its my pleasure",
        "It was nothing",
        "I am happy to help",
        "Not at all",
        "Sure",
        "Thats okay",
        "Thats alright",
        "Anytime"
        ] %}
        {% set rindex =  (range(0, (responses | length - 1) )|random) -%}
        {{responses[rindex]}}'
        