---
# This alerts me on my iPhone when a new release
# of Home Assistant for Hass.io is released.
#
- alias: system_upgrade_alert
  trigger:
    platform: state
    entity_id: sensor.version_available
  condition:
    - condition: template
      value_template: >-
        {{ states('sensor.version_available') != states('sensor.version_current') }}
  action:
    - service: script.notify_manager_set
      data_template:
        notify_title: Upgrade time!
        notify_say: >-
          There is a Home Assistant upgrade for Hass.io pending!
          Version {{ states('sensor.version_available') }} just got released!
        notify_display: >-
          There is a Home Assistant upgrade for Hass.io pending!
          Version {{ states('sensor.version_available') }} just got released!
        notify_id: hassio_upgrade
        notify_dest: DennisPhone
        notify_level: 2
      
    
- alias: system_upgrade_alert_expired
  trigger:
    platform: state
    entity_id: sensor.version_current
  condition:
    - condition: template
      value_template: >-
        {{ states('sensor.version_available') == states('sensor.version_current') }}
  action:
    - service: script.notify_manager_clear
      data_template:
        notify_id: hassio_upgrade