
- alias: Notification Stretch
  trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '0'
  action:
    - service: script.notify
      data_template:
        notify_display: >
          Time to stretch.
        notify_say: "Time to stretch."
        notify_level: 2
        notify_dest: 'DennisPhone'