
- alias: "Notification HA start-up"
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: script.zanzito_say
    data:
      dest_id: "DennisPhone" 
      message: "System restart complete.."    