
- alias: "Notification HA start-up"
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: shell_command.say
    data:
      dest_id: "default" 
      message: "'System restart complete..'"    