
- alias: "Notification DNS Expiration Warning us"
  trigger:
  - platform: sun
    event: sunrise
  condition:
  - condition: numeric_state
    entity_id: sensor.dns1
    below: 30
  action:
  - service: script.notify
    data_template:
      notify_display: "DNS resistration is expiring for " !secret dns1 " in {{ states.sensor.dns1.state }} days."
      notify_dest: "DennisPhone" 
      notify_say: "DNS registration is expiring for " !secret dns1 " in {{ states.sensor.dns1.state }} days."
      notify_title: "DNS Expiring"
      notify_level: 1
      notify_id: "dns1_alert"
      


- alias: "Notification DNS Expiration Warning org"
  trigger:
  - platform: sun
    event: sunrise
  condition:
  - condition: numeric_state
    entity_id: sensor.dns2
    below: 30
  action:
  - service: script.notify
    data_template:
      notify_display: "DNS resistration is expiring for .org in {{ states.sensor.dns2.state }} days."
      notify_dest: "DennisPhone" 
      notify_say: "DNS registration is expiring for .org in {{ states.sensor.dns2.state }} days."
      notify_title: "DNS Expiring"
      notify_level: 1
      notify_id: "dns2_alert"      