      
- alias: Notification Phone hot
  trigger:
  - platform: numeric_state
    entity_id: sensor.phone_temperature
    above: 95
  action:
  - service: script.notify_manager_set
    data_template:
      notify_dest: "DennisPhone" 
      notify_display: >
                        "Phone temperature has risen to {{ states.sensor.phone_temperature.state }} F."
      notify_level: 3
      notify_id: "phonehot_alert"  
      notify_say: "Your phone is now {{ states.sensor.phone_temperature.state }} degrees fahrenheit."
      notify_title: "Phone Hot"
      