      
- alias: Notification Aurora Visibility
  trigger:
  - platform: state
    entity_id: binary_sensor.aurora_visibility
    from: 'off'
    to: 'on'
  action:
  - service: script.notify
    data_template:
      notify_dest: "DennisPhone" 
      notify_say: >
                There is currently a {{ states.binary_sensor.aurora_visibility.attributes.visibility_level }} % chance of viewing auroras.  
                {{ states.binary_sensor.aurora_visibility.attributes.message }}
      notify_display: >
                There is currently a {{ states.binary_sensor.aurora_visibility.attributes.visibility_level }} % chance of viewing auroras.  
                {{ states.binary_sensor.aurora_visibility.attributes.message }}
      notify_title: "Aurora Alert"
      notify_id: "aurora_alert" 
      notify_level: 2
      
      
- alias: Notification Aurora Expiration
  trigger:
  - platform: state
    entity_id: binary_sensor.aurora_visibility
    from: 'on'
    to: 'off'
  action:
  - service: script.notify_clear
    data_template:
      notify_dest: "DennisPhone" 
      notify_display: >
                The chance of viewing auroras has passed.
      notify_id: "aurora_alert" 