
- alias: Notify Phone mostly charged
  trigger:
  - platform: numeric_state
    entity_id: sensor.phone_battery
    above: '94'
  action:
  - service: script.zanzito_say
    data:
      dest_id: "DennisPhone" 
      message: "Phone mostly charged"

      
- alias: Notify Phone charging
  trigger:
  - platform: state
    entity_id: sensor.phone_charging
    from: 'False'
    to: 'True'
  action:
  - service: script.zanzito_say
    data:
      dest_id: "DennisPhone" 
      message: "Phone charging initiated"
      
- alias: Notify Phone charging ended
  trigger:
  - platform: state
    entity_id: sensor.phone_charging
    from: 'True'
    to: 'False'
  condition: 
    condition: numeric_state
    entity_id: sensor.phone_battery
    below: 100
  action:
  - service: script.zanzito_say
    data:
      dest_id: "DennisPhone" 
      message: "Phone no longer charging"

- alias: Notify Phone charged
  trigger:
  - platform: state
    entity_id: sensor.phone_charging
    from: 'True'
    to: 'False'
  condition: 
    condition: numeric_state
    entity_id: sensor.phone_battery
    above: 99
  action:
  - service: script.zanzito_say
    data:
      dest_id: "DennisPhone" 
      message: "Phone charging complete"
      
- alias: Notify Phone low
  trigger:
  - platform: numeric_state
    entity_id: sensor.phone_battery
    below: '50'
  action:
  - service: script.send_alert
    data:
      dest_id: "DennisPhone" 
      message: "Warning!  Phone battery below 50% charge."
  - service: persistent_notification.create
    data:
      message: "Phone Battery below 50%"
      title: "Phone Low"
      notification_id: phone_batt_low
      
- alias: Notify Phone very low
  trigger:
  - platform: numeric_state
    entity_id: sensor.phone_battery
    below: '26'
  action:
  - service: script.zanzito_say
    data:
      dest_id: "DennisPhone" 
      message: "Warning!  Phone battery below 25% charge."
  - service: persistent_notification.create
    data:
      message: "Phone Battery below 25%"
      title: "Phone Low"
      notification_id: phone_batt_very_low