
- alias: "Notify HA shutdown"
  trigger:
  - platform: homeassistant
    event: shutdown
  - platform: event   
    event_type: homeassistant.restart
 
  action:
  - service: script.zanzito_say
    data:
      dest_id: "DennisPhone" 
      message: "Home automation system shutting down."    