##############################################################################
###  New Device has connected to the network.  let everyone know.
##############################################################################

- alias: "Notification New device connected"
  trigger:
    - platform: event
      event_type: device_tracker_new_device

  action:
#    - wait_template: >-
#        {{ not is_state('media_player.livingroomCC', 'playing') }}

    - service: script.notify
      data_template:
        notify_dest: "DennisPhone" 
        notify_say: 'There has been a new device detected on the network.  Be sure to appropriately catagorize {{ trigger.event.data.host_name }} .'
        notify_display: "New device detected on the network!  {{ trigger.event.data.host_name }} {{ trigger.event.data.ip }}"
        notify_title: "IP"
        notify_id: "ip_alert"        

 ##############################################################################
