
- alias: "Notification DNS Expiration Warning"
  trigger:
  - platform: sun
    event: sunrise
  condition:
  - condition: numeric_state
    entity_id: sensor.sellfamily_us
    below: 58
  - condition: numeric_state
    entity_id: sensor.sellfamily_org
    below: 58
  action:
  - service: script.notify
    data_template:
      notify_display: "DNS resistration is expiring for "
      notify_dest: "DennisPhone" 
      notify_say: "DNS registration is expiring for "
      notify_title: "DNS Expiring"
      notify_level: 1
      notify_id: "dns_alert"