- alias: Notification Dinner Bell On
  trigger:
  - platform: state
    entity_id: input_boolean.dinner_bell
    from: 'off'
    to: 'on'
  action:
    - service: shell_command.play
      data:
        file: "/config/audio/dinner_bell.wav"
        
        
- alias: Notification Dinner Bell Off
  trigger:
  - platform: state
    entity_id: input_boolean.dinner_bell
    from: 'on'
    to: 'off'
  action:
    - service: script.notify_clear
      data:
        notify_id: dinner_bell