
- alias: "Notification DNS Expiration Warning Sellfamily.us"
  trigger:
  - platform: sun
    event: sunrise
  condition:
  - condition: numeric_state
    entity_id: sensor.sellfamily_us
    below: 30
  action:
  - service: script.notify
    data_template:
      notify_display: "DNS resistration is expiring for sellfamily.us in {{ states.sensor.sellfamily_us.state }} days."
      notify_dest: "DennisPhone" 
      notify_say: "DNS registration is expiring for sellfamily.us in {{ states.sensor.sellfamily_us.state }} days."
      notify_title: "DNS Expiring"
      notify_level: 1
      notify_id: "dns1_alert"
      


- alias: "Notification DNS Expiration Warning Sellfamily.org"
  trigger:
  - platform: sun
    event: sunrise
  condition:
  - condition: numeric_state
    entity_id: sensor.sellfamily_org
    below: 30
  action:
  - service: script.notify
    data_template:
      notify_display: "DNS resistration is expiring for sellfamily.org in {{ states.sensor.sellfamily_org.state }} days."
      notify_dest: "DennisPhone" 
      notify_say: "DNS registration is expiring for sellfamily.org in {{ states.sensor.sellfamily_org.state }} days."
      notify_title: "DNS Expiring"
      notify_level: 1
      notify_id: "dns2_alert"      