
- alias: Notification Phone mostly charged
  trigger:
  - platform: numeric_state
    entity_id: sensor.phone_battery
    above: '94'
  action:
  - service: script.zanzito_say
    data:
      dest_id: "default" 
      message: "'Phone mostly charged'"

      
- alias: Notification Phone charging
  trigger:
  - platform: state
    entity_id: sensor.phone_charging
    from: 'False'
    to: 'True'
  action:
  - service: script.zanzito_say
    data:
      dest_id: "default" 
      message: "'Phone charging initiated'"
      
- alias: Notification Phone charging ended
  trigger:
  - platform: state
    entity_id: sensor.phone_charging
    from: 'True'
    to: 'False'
  condition: 
    condition: numeric_state
    entity_id: sensor.phone_battery
    below: 100
  action:
  - service: script.zanzito_say
    data:
      dest_id: "default" 
      message: "'Phone no longer charging'"

- alias: Notification Phone charged
  trigger:
  - platform: state
    entity_id: sensor.phone_charging
    from: 'True'
    to: 'False'
  condition: 
    condition: numeric_state
    entity_id: sensor.phone_battery
    above: 99
  action:
  - service: script.zanzito_say
    data:
      dest_id: "default" 
      message: "'Phone charging complete'"
      
- alias: Notification Phone low
  trigger:
  - platform: numeric_state
    entity_id: sensor.phone_battery
    below: '50'
  action:
  - service: script.notify
    data:
      notify_dest: "default" 
      notify_say: "'Warning!  Phone battery below 50% charge.'"
      notify_display: "Phone Battery below 50%"
      notify_title: "Phone Low"
      notify_id: 'phone_batt_low'
      
- alias: Notification Phone very low
  trigger:
  - platform: numeric_state
    entity_id: sensor.phone_battery
    below: '26'
  action:
  - service: script.zanzito_say
    data:
      dest_id: "default" 
      message: "'Warning!  Phone battery below 25% charge.'"
  - service: persistent_notification.create
    data:
      message: "Phone Battery below 25%"
      title: "Phone Low"
      notification_id: phone_batt_very_low