- alias: NWS Alert Issued
  trigger:
    platform: state
    entity_id: sensor.nws_alerts
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ trigger.from_state.state < trigget.to_state.state }}'
    - condition: template
      value_template: '{{ trigger.from_state.state < 1 }}'
  action:
  - service: script.notify_manager_set
    data_template:
      notify_dest: "DennisPhone" 
      notify_say: "The National Weather Service has issued one or more alerts.  {{ states.sensor.nws_alerts.attributes.spoken_desc }}"
      notify_display: "{{ states.sensor.nws_alerts.attributes.display_desc }}"
      notify_title: "NWS warning(s) issued: {{ states.sensor.nws_alerts.attributes.title }}"
      notify_id: nws_alert     


- alias: NWS Additional Alert
  trigger:
    platform: state
    entity_id: sensor.nws_alerts
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ trigger.from_state.state < trigget.to_state.state }}'
      - condition: template
        value_template: '{{ trigger.from_state.state > 0 }}'
  action:
  - service: script.notify_manager_set
    data_template:
      notify_dest: "DennisPhone" 
      notify_say: "The National Weather Service has issued one or more additional alerts.  {{ states.sensor.nws_alerts.attributes.spoken_desc }}"
      notify_display: "{{ states.sensor.nws_alerts.attributes.display_desc }}"
      notify_title: "NWS warning(s) issued: {{ states.sensor.nws_alerts.attributes.title }}"
      notify_id: nws_alert     
     

- alias: NWS Some Alerts Expired
  trigger:
    platform: state
    entity_id: sensor.nws_alerts
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ trigger.from_state.state > trigget.to_state.state }}'
    - condition: template
      value_template: '{{ trigger.to_state.state > 0 }}'
  action:
  - service: script.notify_manager_set
    data:
      notify_dest: "DennisPhone" 
      notify_say: "One or more National Weather Service alerts have expired."
      notify_display: "Weather alert warnings expired."
      notify_title: "NWS"
      notify_id: nws_alert   

      
- alias: NWS All Alerts Expired
  trigger:
  - platform: numeric_state
    entity_id: sensor.nws_alerts
    below: '1'
  action:
  - service: script.notify_manager_clear
    data:
      notify_dest: "DennisPhone" 
      notify_say: "All National Weather Service alerts have expired."
      notify_id: "nws_alert"      
      
