- alias: NWS Alert
  trigger:
  - platform: numeric_state
    entity_id: sensor.nws_alerts
    above: '0'
  action:
  - service: script.zanzito_say
    data:
      dest_id: "DennisPhone" 
      message: "The National Weather Service has issued one or more alerts."
  - service: persistent_notification.create
    data:
      message: "Weather alert warnings issued!"
      title: "NWS"
      notification_id: nws_alert      

- alias: NWS Alert Expired
  trigger:
  - platform: numeric_state
    entity_id: sensor.nws_alerts
    below: '1'
  action:
  - service: script.zanzito_say
    data:
      dest_id: "DennisPhone" 
      message: "The National Weather Service alerts have expired."
  - service: persistent_notification.dismiss
    data:
      notification_id: "nws_alert"      
      
