
      
- alias: Phone photo switch goes on
  trigger:
  - platform: state
    entity_id: input_boolean.zanzito_take_photo
    from: 'off'
    to: 'on'
  action:
  - service: script.zanzito_take_photo
  - service: input_boolean.turn_off
    entity_id: input_boolean.zanzito_take_photo
          
- alias: Phone alarm switch goes on
  trigger:
  - platform: state
    entity_id: input_boolean.zanzito_play_alarm
    from: 'off'
    to: 'on'
  action:
  - service: script.zanzito_play_alarm
    data:
      dest_id: 'DennisPhone'
      message: ''
      
- alias: Phone alarm switch goes off
  trigger:
  - platform: state
    entity_id: input_boolean.zanzito_play_alarm
    from: 'on'
    to: 'off'
  action:
  - service: script.zanzito_stop_alarm
    data:
      dest_id: 'DennisPhone'      

- alias: Phone Alarm ack
  trigger:
  - platform: state
    entity_id: binary_sensor.zanzito_alarm_ack
    to: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.zanzito_play_alarm
    