- alias: Notification Shop Activity
  trigger:
  - platform: state
    entity_id: binary_sensor.test_motion
    from: 'off'
    to: 'on'
  action:
  - service: script.notify
    data_template:
      notify_dest: "default" 
      notify_say: "'Shop activity detected'"
      notify_display: "Shop activity detected" 
      notify_title: "Shop Activity"
      notify_level: 1
      notify_id: shop_alert  