     
- alias: Security Shop Activity
  trigger:
  - platform: state
    entity_id: input_boolean.shop_motion
    from: 'off'
    to: 'on'      
  action:
  - service: script.zanzito_say
    data:
      dest_id: "DennisPhone" 
      message: "Shop motion detected."
      
- alias: Security Shop Door Activity
  trigger:
  - platform: state
    entity_id: input_boolean.shop_door_motion
    from: 'off'
    to: 'on'      
  action:
  - service: script.zanzito_say
    data:
      dest_id: "DennisPhone" 
      message: "Shop door motion detected."      