- alias: Turn Shop Lights On
  trigger:
  - platform: state
    entity_id: binary_sensor.test_motion
    from: 'off'
    to: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.sonoff5_power_state



- alias: Turn Shop Lights Off
  trigger:
  - platform: state
    entity_id: binary_sensor.test_motion
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
  - service: switch.turn_off
    entity_id: switch.sonoff5_power_state
    