- alias: 'Test'
  trigger:
    - platform: state
      entity_id: binary_sensor.test_motion
      from: 'off'
      to: 'on'
  action:
    - service: script.zanzito_say
      data:
        message: "I C U"
        dest_id: DennisPhone