- alias: 'Test'
  trigger:
    - platform: state
      entity_id: binary_sensor.test_motion
      from: 'off'
      to: 'on'
  action:
    - service: shell_command.say
      data:
        message: "hello world"