
- alias: "Toggle April fools On"
  trigger:
    platform: sun
    event: sunrise
  condition:
    condition: template
    value_template: '{{ now().strftime("%m-%d") == "04-01" }}'
  action:
  - service: mqtt.publish
    data_template:
      payload: 'true'
      topic: 'cmnd/D1mini1/SetOption16'
      qos: 1
      retain: true    
      

- alias: "Toggle April fools Off"
  trigger:
    platform: sun
    event: sunrise
  condition:
    condition: template
    value_template: '{{ now().strftime("%m-%d") == "04-02" }}'
  action:
  - service: mqtt.publish
    data_template:
      payload: 'false'
      topic: 'cmnd/D1mini1/SetOption16'
      qos: 1
      retain: true