---
# The version sensor platform is displaying the
# available version online.
#
# https://www.home-assistant.io/components/sensor.version/
#
- platform: version
  name: Version Available
  source: hassio
  image: qemux86-64