- platform: mqtt
  name: "Phone Battery Raw"
  state_topic: "zanzito/DennisPhone/battery_level"
  qos: 0
  unit_of_measurement: "%"
    
- platform: filter
  name: "Phone Battery"
  entity_id: sensor.phone_battery_raw
  filters:
    - filter: outlier
      window_size: 4
      radius: 6.0  
      
- platform: mqtt
  name: "Phone Temperature Raw"
  state_topic: "zanzito/DennisPhone/shtc1_ambient_temperature_sensor"
  value_template: "{{ (value | float * 1.8 | float + 32) | round(2) }}"
  qos: 0
  unit_of_measurement: "F"
  device_class: temperature

- platform: filter
  name: "Phone Temperature"
  entity_id: sensor.phone_temperature_raw
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0  

- platform: mqtt
  name: "Phone Barometric Pressure Raw"
  state_topic: "zanzito/DennisPhone/barometer_sensor"
  value_template: "{{ (value | float * 0.029529983071445) | round(2) }}"
  qos: 0
  unit_of_measurement: "in Hg"
  device_class: pressure
  
- platform: filter
  name: "Phone Barometric Pressure"
  entity_id: sensor.phone_barometric_pressure_raw
  filters:
    - filter: range
      upper_bound: 33
      lower_bound: 28
  
- platform: mqtt
  name: "Phone Humidity Raw"
  state_topic: "zanzito/DennisPhone/shtc1_relative_humidity_sensor"
  qos: 0
  unit_of_measurement: "%"
  device_class: humidity
  
- platform: filter
  name: "Phone Humidity"
  entity_id: sensor.phone_humidity_raw
  filters:
    - filter: outlier
      window_size: 4
      radius: 4.0  
  
- platform: mqtt
  name: "Phone Steps"
  state_topic: "zanzito/DennisPhone/samsung_step_counter_sensor"
  qos: 0
  
- platform: mqtt
  name: "Phone Screen Locked"
  value_template: '{{ value_json.screen_locked }}'
  state_topic: "zanzito/DennisPhone/device_info"
  qos: 0

- platform: mqtt
  name: "Phone Plugged In"
  state_topic: "zanzito/DennisPhone/device_info"
  value_template: '{{ value_json.charge_type }}'
  qos: 0  
  
- platform: mqtt
  name: "Phone Charging"
  state_topic: "zanzito/DennisPhone/device_info"
  value_template: '{{ value_json.battery_charging }}'
  qos: 0  

- platform: mqtt
  name: "Phone Screen On"
  state_topic: "zanzito/DennisPhone/device_info"
  value_template: '{{ value_json.screen_on }}'
  qos: 0  
  
- platform: mqtt
  name: "Phone Screen Orientation"
  state_topic: "zanzito/DennisPhone/device_info"
  value_template: '{{ value_json.screen_orientation }}'
  qos: 0  
  
- platform: mqtt
  name: "Phone Foreground App"
  state_topic: "zanzito/DennisPhone/device_info"
  value_template: '{{ value_json.current_foreground_app }}'
  qos: 0  
  
- platform: mqtt
  name: "Phone WiFi"
  state_topic: "zanzito/DennisPhone/device_info"
  value_template: '{{ value_json.current_wifi }}'
  qos: 0  
  
- platform: mqtt
  name: "Phone Carrier"
  state_topic: "zanzito/DennisPhone/device_info"
  value_template: '{{ value_json.current_operator }}'
  qos: 0    
  
- platform: mqtt
  name: "Phone Acc X"
  state_topic: "zanzito/DennisPhone/k330_3-axis_accelerometer"
  value_template: '{{ value_json.value0 }}'
  qos: 0    
  unit_of_measurement: "m/s^2" 
  
- platform: mqtt
  name: "Phone Acc Y"
  state_topic: "zanzito/DennisPhone/k330_3-axis_accelerometer"
  value_template: '{{ value_json.value1 }}'
  qos: 0    
  unit_of_measurement: "m/s^2" 
  
- platform: mqtt
  name: "Phone Acc Z"
  state_topic: "zanzito/DennisPhone/k330_3-axis_accelerometer"
  value_template: '{{ value_json.value2 }}'
  qos: 0    
  unit_of_measurement: "m/s^2"    